#!/usr/bin/env python3
"""
OpenDash Image Converter
Automatically converts JPG/PNG images to LVGL-compatible C arrays.

This script:
1. Scans for background and splash images in source/
2. Scales images proportionally to fit display resolutions
3. Converts to RGB565 format
4. Generates C header files for LVGL

Usage:
    ./convert_images.py              # Convert all images
    ./convert_images.py --force      # Force re-conversion
    ./convert_images.py --check      # Check dependencies
"""

import os
import sys
import subprocess
from pathlib import Path
from typing import Dict, List, Tuple, Optional

# Color codes for terminal output
class Colors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def print_info(msg: str):
    """Print info message"""
    print(f"{Colors.OKBLUE}[INFO]{Colors.ENDC} {msg}")

def print_success(msg: str):
    """Print success message"""
    print(f"{Colors.OKGREEN}[SUCCESS]{Colors.ENDC} {msg}")

def print_warning(msg: str):
    """Print warning message"""
    print(f"{Colors.WARNING}[WARNING]{Colors.ENDC} {msg}")

def print_error(msg: str):
    """Print error message"""
    print(f"{Colors.FAIL}[ERROR]{Colors.ENDC} {msg}")

# Display resolutions
DISPLAY_RESOLUTIONS = {
    'center': (800, 480),
    'leftright': (480, 480),
    'gps': (466, 466)
}

def check_imagemagick_installed() -> bool:
    """Check if ImageMagick is installed"""
    try:
        result = subprocess.run(['convert', '--version'], 
                              capture_output=True, text=True, check=True)
        print_success(f"ImageMagick is installed")
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        print_error("ImageMagick is not installed")
        print_info("Install ImageMagick: sudo apt-get install imagemagick")
        return False

def check_python_pil() -> bool:
    """Check if Python PIL/Pillow is available"""
    try:
        from PIL import Image
        print_success("Python PIL/Pillow is available")
        return True
    except ImportError:
        print_warning("Python PIL/Pillow not available - using ImageMagick only")
        return False

def scale_image_proportional(input_path: Path, output_path: Path, 
                             target_width: int, target_height: int) -> bool:
    """Scale image proportionally to fit target resolution"""
    try:
        # Use ImageMagick to scale with aspect ratio preservation
        # -resize: scale to fit within dimensions
        # -background black: fill empty space with black
        # -gravity center: center the image
        # -extent: ensure final size matches target
        cmd = [
            'convert',
            str(input_path),
            '-resize', f'{target_width}x{target_height}',
            '-background', 'black',
            '-gravity', 'center',
            '-extent', f'{target_width}x{target_height}',
            str(output_path)
        ]
        
        subprocess.run(cmd, check=True, capture_output=True)
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"Failed to scale image: {e}")
        return False

def convert_image_to_c_array(input_path: Path, output_path: Path, 
                             var_name: str, width: int, height: int) -> bool:
    """Convert image to C array in RGB565 format"""
    try:
        # Convert to raw RGB888 format
        cmd_rgb = [
            'convert',
            str(input_path),
            '-depth', '8',
            '-size', f'{width}x{height}',
            'RGB:-'
        ]
        
        result = subprocess.run(cmd_rgb, check=True, capture_output=True)
        rgb_data = result.stdout
        
        # Convert RGB888 to RGB565
        rgb565_data = []
        for i in range(0, len(rgb_data), 3):
            r = rgb_data[i] >> 3      # 5 bits
            g = rgb_data[i+1] >> 2    # 6 bits
            b = rgb_data[i+2] >> 3    # 5 bits
            rgb565 = (r << 11) | (g << 5) | b
            rgb565_data.append(rgb565)
        
        # Generate C header file
        header_content = f"""/**
 * @file {output_path.name}
 * @brief Auto-generated image data for OpenDash
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by convert_images.py
 * 
 * Image: {input_path.name}
 * Resolution: {width}x{height}
 * Format: RGB565
 */

#ifndef {var_name.upper()}_H
#define {var_name.upper()}_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define {var_name.upper()}_WIDTH  {width}
#define {var_name.upper()}_HEIGHT {height}

extern const uint16_t {var_name}[{len(rgb565_data)}];

#ifdef __cplusplus
}}
#endif

#endif /* {var_name.upper()}_H */
"""
        
        # Write header file
        with open(output_path, 'w') as f:
            f.write(header_content)
        
        # Generate C source file
        c_file = output_path.with_suffix('.c')
        c_content = f"""/**
 * @file {c_file.name}
 * @brief Auto-generated image data for OpenDash
 */

#include "{output_path.name}"

const uint16_t {var_name}[{len(rgb565_data)}] = {{
"""
        
        # Write pixel data in rows of 12 values for readability
        for i in range(0, len(rgb565_data), 12):
            row = rgb565_data[i:i+12]
            c_content += "    "
            c_content += ", ".join(f"0x{val:04X}" for val in row)
            if i + 12 < len(rgb565_data):
                c_content += ","
            c_content += "\n"
        
        c_content += "};\n"
        
        with open(c_file, 'w') as f:
            f.write(c_content)
        
        print_success(f"  Generated: {output_path.name}")
        return True
        
    except Exception as e:
        print_error(f"Failed to convert image to C array: {e}")
        return False

def process_image(source_path: Path, display: str, image_type: str,
                 output_dir: Path, force: bool = False) -> int:
    """Process a single image file"""
    
    if not source_path.exists():
        return 0  # Not an error, just no image
    
    width, height = DISPLAY_RESOLUTIONS[display]
    var_name = f"{image_type}_{display}"
    
    # Output paths
    scaled_path = output_dir / f"{var_name}_scaled.png"
    header_path = output_dir / f"{var_name}.h"
    
    # Check if conversion needed
    if not force and header_path.exists() and scaled_path.exists():
        # Skip if source is older than both generated files (meaning they're up to date)
        source_mtime = source_path.stat().st_mtime
        scaled_mtime = scaled_path.stat().st_mtime
        header_mtime = header_path.stat().st_mtime
        
        if source_mtime <= scaled_mtime and source_mtime <= header_mtime:
            print_info(f"  {var_name}: Up to date, skipping")
            return 0
    
    print_info(f"  Processing {source_path.name} for {display} display...")
    
    # Step 1: Scale image proportionally
    if not scale_image_proportional(source_path, scaled_path, width, height):
        return 1
    
    # Step 2: Convert to C array
    if not convert_image_to_c_array(scaled_path, header_path, var_name, width, height):
        return 1
    
    print_success(f"  Converted {image_type} for {display}: {width}x{height}")
    return 0

def main():
    """Main entry point"""
    force = '--force' in sys.argv
    check_only = '--check' in sys.argv
    
    print(f"{Colors.BOLD}OpenDash Image Converter{Colors.ENDC}")
    print("=" * 60)
    
    # Get paths
    script_dir = Path(__file__).parent
    source_dir = script_dir / 'source'
    output_dir = script_dir / 'generated'
    
    # Check prerequisites
    if not check_imagemagick_installed():
        return 1
    
    check_python_pil()  # Optional, just informs user
    
    if check_only:
        print_success("Setup check complete - ready for image conversion")
        return 0
    
    # Ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Process images for each display
    print_info("Scanning for images...")
    print("=" * 60)
    
    total_errors = 0
    images_processed = 0
    
    for display in DISPLAY_RESOLUTIONS.keys():
        print_info(f"Processing {display} display...")
        
        # Check for background image
        for ext in ['.jpg', '.jpeg', '.png']:
            bg_path = source_dir / f"background_{display}{ext}"
            if bg_path.exists():
                result = process_image(bg_path, display, 'background', output_dir, force)
                total_errors += result
                if result == 0:
                    images_processed += 1
                break
        
        # Check for splash image
        for ext in ['.jpg', '.jpeg', '.png']:
            splash_path = source_dir / f"splash_{display}{ext}"
            if splash_path.exists():
                result = process_image(splash_path, display, 'splash', output_dir, force)
                total_errors += result
                if result == 0:
                    images_processed += 1
                break
    
    print("=" * 60)
    if images_processed == 0:
        print_info("No images found to process")
        print_info(f"Place images in: {source_dir}/")
        print_info("  background_<display>.jpg/png - Background image")
        print_info("  splash_<display>.jpg/png - Boot splash")
        print_info("  Where <display> is: center, leftright, or gps")
    elif total_errors == 0:
        print_success(f"Image conversion completed successfully!")
        print_success(f"Processed {images_processed} image(s)")
        print_info(f"Generated files are in: {output_dir}")
    else:
        print_error(f"Image conversion failed with {total_errors} error(s)")
        return 1
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
