/* Licensed under Sovereign Individual License v1.0 — see LICENSE file */
/**
 * @file ui_manager.c
 * @brief OpenDash Left/Right/Pod Gauges — UI Manager Implementation
 *
 * Creates a professional gauge layout for the round 480x480 displays.
 * Shared by /left, /right, and future /pod# projects.
 *
 * ====================================================================
 *  MULTI-PAGE GAUGE SYSTEM
 * ====================================================================
 *
 *  The display cycles through N gauge pages + 1 odometer page.
 *  All gauge pages share a SINGLE set of LVGL widgets (screen_gauge).
 *  On page switch the labels, unit suffixes, and arc range are swapped
 *  instantly — no screen objects are created or destroyed.
 *
 *  Default pages (configurable via s_gauge_pages[]) — page 0 is boot default:
 *    Page 0: WHEEL SPEED MPH (arc) + GPS MPH (box)   [known-data default]
 *    Page 1: OIL PRESS (arc)       + BOOST (box)
 *    Page 2: WATER TEMP (arc)      + WHEEL MPH (box)
 *    Page 3: RPM (arc)             + AFR (box)       [shift-light enabled]
 *    Page 4: Odometer / Trip A
 *
 * ====================================================================
 *  GAUGE SCREEN LAYOUT  (480x480 Round Display)
 * ====================================================================
 *
 *               480 px
 *    +------------------------------+
 *   /                                \
 *  |  +-- Arc (270deg sweep) ------+  |
 *  |  | Outer: ARC_SIZE px         |  |   ARC_WIDTH = 45px
 *  |  | Width: 45px                |  |   ARC_OUTLINE_EXTRA = 5px
 *  |  | Outline: +5px symmetric    |  |   (extends 5px inside AND outside)
 *  |  |                            |  |
 *  |  |  +== Primary Value ======+ |  |   XXLARGE (96px) font
 *  |  |  |  "OIL PRESS"  (label) | |  |   Centered in display
 *  |  |  |    "47.2"      (value) | |  |
 *  |  |  |    "psi"       (unit)  | |  |
 *  |  |  |  MIN: 32  MAX: 68     | |  |   SMALL font, session high/low
 *  |  |  +========================+ |  |
 *  |  |                            |  |
 *  |  +--------+    +--------------+  |   90deg gap at bottom
 *  |       +-------------------+       |
 *  |       | BOOST      <-label|       |   +- SECONDARY BOX ----------+
 *  |       |     14.7   <-val  |       |   | 200x100 px, Y=+150      |
 *  |       |            kPa <-u|       |   | Label: TOP_LEFT  MED     |
 *  |       +-------------------+       |   | Value: CENTER    XLARGE  |
 *   \                                /    | Unit:  BOT_RIGHT MED     |
 *    +------------------------------+     +---------------------------+
 *
 * @see LVGL Documentation: https://docs.lvgl.io/master/
 * @see opendash_ui_styles.h for color definitions
 * @see opendash_fonts.h for font size definitions
 */

#include "ui_manager.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "lvgl.h"
#include "opendash_common.h"
#include "opendash_data_model.h"
#include "opendash_fonts.h"
#include "opendash_ui_styles.h"
#include <string.h>
#include <stdio.h>
#include <math.h>

/* ======================================================================
 * Conditionally include background image.
 *
 * The image header is auto-generated by common/images/convert_images.py.
 * If the header doesn't exist (images not converted), the UI still works
 * with a plain black background.
 * ====================================================================== */
#if __has_include("background_right.h")
#include "background_right.h"
#define HAS_BACKGROUND_IMAGE 1
#elif __has_include("background_leftright.h")
#include "background_leftright.h"
#define HAS_BACKGROUND_IMAGE 1
#define background_right_dsc background_leftright_dsc
#else
#define HAS_BACKGROUND_IMAGE 0
#endif

static const char *TAG = "ui_manager";

/* ======================================================================
 * LAYOUT CONSTANTS — All dimensions in pixels
 *
 * +---------------------------------------------------------------------+
 * | To adjust the layout, change ONLY these constants.                   |
 * | Each constant has a comment showing what it controls on screen.      |
 * +---------------------------------------------------------------------+
 * ====================================================================== */

/* --- Display geometry --- */
#define LCD_H_RES               480     /* Horizontal resolution (pixels) */
#define LCD_V_RES               480     /* Vertical resolution (pixels) */

/* --- Arc gauge dimensions ---
 *     TWO concentric arcs are drawn:
 *       1) White outline arc — LARGER bounding box, wider stroke
 *       2) Colored indicator — smaller bounding box, normal stroke
 *
 *     LVGL draws arcs INWARD from the bounding-box outer edge.
 *     To get a symmetric outline (N px on EACH side of the colored arc):
 *       - Outline size  = ARC_SIZE + 2*OUTLINE_EXTRA  (extends outside)
 *       - Outline width = ARC_WIDTH + 2*OUTLINE_EXTRA (extends inside)
 *
 *     Visual proof (radii, center of display = 0):
 *       Outline outer = (ARC_SIZE+2*5)/2 = 230   Colored outer = 450/2 = 225
 *       Outline inner = 230 - 55 = 175            Colored inner = 225 - 45 = 180
 *       Outside gap = 230 - 225 = 5px  ✓          Inside gap = 180 - 175 = 5px  ✓
 */
#define ARC_SIZE                450     /* Colored arc bounding box (px) */
#define ARC_WIDTH               45      /* Colored arc stroke thickness (px) */
#define ARC_OUTLINE_EXTRA       5       /* Outline extension per side (px) */
#define ARC_OUTLINE_SIZE        (ARC_SIZE + ARC_OUTLINE_EXTRA * 2)  /* 460px */
#define ARC_OUTLINE_WIDTH       (ARC_WIDTH + ARC_OUTLINE_EXTRA * 2) /* 55px  */
#define ARC_ROTATION_DEG        135     /* Start angle of arc sweep (degrees) */
#define ARC_SWEEP_DEG           270     /* Total sweep angle (degrees) */
#define ARC_Y_OFFSET            0       /* Y offset from center (px, + = down) */

/* --- Primary value area (upper half of screen, inside arc) ---
 *     Shows the main gauge label and numeric value.
 *     Example: "OIL TEMP" / "225" / "deg F"
 */
#define PRIMARY_LABEL_Y         (-90)   /* Label Y offset from center (px, up) */
#define PRIMARY_VALUE_Y         (-25)   /* Value Y offset from center (px) */
#define PRIMARY_UNIT_Y          35      /* Unit suffix Y offset (px) */
#define PRIMARY_MINMAX_Y        65      /* Min/Max text Y offset (px) */

/* --- Secondary value box (bottom of screen, inside arc gap) ---
 *     A bordered rectangle showing a second reading.
 *     Width is sized to fit between the inner edges of the arc
 *     at the bottom (~247px gap); we use 200px for comfortable margins.
 */
#define SECONDARY_BOX_W         200     /* Box width (px) */
#define SECONDARY_BOX_H         115     /* Box height (px) — was 85→100→115 for readability */
#define SECONDARY_BOX_Y         150     /* Box center Y offset from screen center */
#define SECONDARY_BOX_RADIUS    8       /* Corner radius (px) */
#define SECONDARY_BOX_BORDER    2       /* Border thickness (px) */
#define SECONDARY_LABEL_Y       2       /* Label Y from TOP of box */
#define SECONDARY_LABEL_X       8       /* Label X from LEFT of box */
#define SECONDARY_VALUE_Y       5       /* Value Y offset from box center */
#define SECONDARY_UNIT_Y        (-4)    /* Unit Y from BOTTOM of box */
#define SECONDARY_UNIT_X        (-8)    /* Unit X from RIGHT of box */

/* --- Odometer area (final screen, upper half) --- */
#define ODO_LABEL_Y             (-110)  /* "ODOMETER" label Y from center */
#define ODO_VALUE_Y             (-55)   /* Odometer reading Y from center */

/* --- Trip box (final screen, same as secondary box) --- */
#define TRIP_BOX_W              SECONDARY_BOX_W
#define TRIP_BOX_H              SECONDARY_BOX_H
#define TRIP_BOX_Y              SECONDARY_BOX_Y
#define TRIP_LABEL_Y            SECONDARY_LABEL_Y
#define TRIP_VALUE_Y            SECONDARY_VALUE_Y

/* --- Warning overlay --- */
#define WARNING_FLASH_MS        100     /* Flash on/off interval (ms) */

/* --- Shift light --- */
#define SHIFT_BLINK_THRESHOLD   90      /* Arc % above which shift-light blinks */
#define SHIFT_BLINK_INTERVAL_MS 150     /* On/off toggle interval (ms) */

/* ======================================================================
 * GAUGE PAGE DEFINITIONS
 *
 * Each entry defines what the primary arc and secondary box display.
 * The last screen is always the odometer (not in this array).
 *
 * To add/remove/reorder pages:
 *   1. Edit s_gauge_pages[] below
 *   2. Rebuild & flash — no other code changes needed.
 * ====================================================================== */

static const gauge_page_t s_gauge_pages[] = {
    /* Page 0 — SPEED (boot default) — Wheel MPH (BMS) + GPS MPH (GPS node).
     * Acts as a "known-data" default so right always has something to show
     * even before OBD2/CAN/BMS-pressure points start streaming. */
    {
        .primary_label      = "SPEED",
        .primary_dp         = OPENDASH_DP_WHEEL_SPEED_AVG,
        .arc_min            = 0.0f,
        .arc_max            = 200.0f,   /* 0-200 km/h → ~0-124 MPH on arc */
        .is_primary_temp    = false,
        .is_primary_pressure = false,
        .is_primary_speed   = true,
        .secondary_label    = "GPS",
        .secondary_dp       = OPENDASH_DP_GPS_SPEED,
        .is_secondary_temp  = false,
        .is_secondary_pressure = false,
        .is_secondary_speed = true,
        .shift_light        = false,
    },
    /* Page 1 — Oil Pressure + Boost */
    {
        .primary_label      = "OIL PRESS",
        .primary_dp         = OPENDASH_DP_OIL_PRESSURE,
        .arc_min            = 0.0f,
        .arc_max            = 700.0f,   /* 0-700 kPa (~0-100 PSI) */
        .is_primary_temp    = false,
        .is_primary_pressure = true,
        .is_primary_speed   = false,
        .secondary_label    = "BOOST",
        .secondary_dp       = OPENDASH_DP_BOOST_PRESSURE,
        .is_secondary_temp  = false,
        .is_secondary_pressure = true,
        .is_secondary_speed = false,
        .shift_light        = false,
    },
    /* Page 2 — Water Temp + Wheel Speed (MPH) */
    {
        .primary_label      = "WATER",
        .primary_dp         = OPENDASH_DP_COOLANT_TEMP,
        .arc_min            = 0.0f,
        .arc_max            = 130.0f,   /* 0-130 deg C full scale */
        .is_primary_temp    = true,
        .is_primary_pressure = false,
        .is_primary_speed   = false,
        .secondary_label    = "SPEED",
        .secondary_dp       = OPENDASH_DP_WHEEL_SPEED_AVG,
        .is_secondary_temp  = false,
        .is_secondary_pressure = false,
        .is_secondary_speed = true,
        .shift_light        = false,
    },
    /* Page 3 — RPM + AFR  (shift-light enabled) */
    {
        .primary_label      = "RPM",
        .primary_dp         = OPENDASH_DP_RPM,
        .arc_min            = 0.0f,
        .arc_max            = 8000.0f,  /* 0-8000 RPM full scale */
        .is_primary_temp    = false,
        .is_primary_pressure = false,
        .is_primary_speed   = false,
        .secondary_label    = "AFR",
        .secondary_dp       = OPENDASH_DP_AFR,
        .is_secondary_temp  = false,
        .is_secondary_pressure = false,
        .is_secondary_speed = false,
        .shift_light        = true,     /* BLINK when RPM > 90% (7200 RPM) */
    },
};

#define GAUGE_PAGE_COUNT    (sizeof(s_gauge_pages) / sizeof(s_gauge_pages[0]))
#define TOTAL_SCREEN_COUNT  (GAUGE_PAGE_COUNT + 1)  /* +1 for odometer */
#define ODO_SCREEN_INDEX    GAUGE_PAGE_COUNT         /* always last */

/* ======================================================================
 * INTERNAL STATE
 * ====================================================================== */

/* Screen objects (only 2 physical screens, gauge pages swap labels) */
static lv_obj_t *screen_gauge = NULL;   /* All gauge pages share this */
static lv_obj_t *screen_odo   = NULL;   /* Odometer / trip page */

/* Gauge screen widgets */
static lv_obj_t *arc_outline      = NULL;
static lv_obj_t *arc_gauge        = NULL;
static lv_obj_t *primary_label    = NULL;
static lv_obj_t *primary_value    = NULL;
static lv_obj_t *primary_unit     = NULL;
static lv_obj_t *primary_minmax   = NULL;  /* "MIN: xx  MAX: yy" */
static lv_obj_t *secondary_box    = NULL;
static lv_obj_t *secondary_label  = NULL;
static lv_obj_t *secondary_value  = NULL;
static lv_obj_t *secondary_unit   = NULL;

/* Odometer screen widgets */
static lv_obj_t *odo_label  = NULL;
static lv_obj_t *odo_value  = NULL;
static lv_obj_t *trip_box   = NULL;
static lv_obj_t *trip_label = NULL;
static lv_obj_t *trip_value = NULL;

/* Warning overlay */
static lv_obj_t   *warning_overlay = NULL;
static lv_timer_t *warning_timer   = NULL;
static opendash_warning_level_t warning_level = OPENDASH_WARNING_NONE;
static uint32_t warning_flash_duration = 0;
static uint32_t warning_flash_start    = 0;

/* Current state */
static opendash_display_layout_t current_layout;
static uint8_t  current_page   = 0;     /* 0..GAUGE_PAGE_COUNT-1 = gauge, ODO_SCREEN_INDEX = odo */
static TaskHandle_t ui_task_handle = NULL;

/* --- Min/Max tracking (per gauge page, per-session) --- */
typedef struct {
    float   primary_min;
    float   primary_max;
    bool    has_data;
} page_minmax_t;

static page_minmax_t s_minmax[GAUGE_PAGE_MAX];

/* --- Shift-light state --- */
static bool     s_shift_active = false;     /* true when arc > threshold */
static uint32_t s_shift_last_toggle_ms = 0;
static bool     s_shift_blink_on = false;

/* ======================================================================
 * HELPER: get display suffix strings for the current page
 * ====================================================================== */

static const char* get_primary_suffix(uint8_t page)
{
    if (page >= GAUGE_PAGE_COUNT) return "";
    const gauge_page_t *p = &s_gauge_pages[page];
    if (p->is_primary_temp)     return opendash_get_temp_suffix(current_layout.temp_unit);
    if (p->is_primary_pressure) return opendash_get_pressure_suffix(current_layout.pressure_unit);
    if (p->is_primary_speed)    return opendash_get_speed_suffix(current_layout.speed_unit);
    /* RPM, ratio, etc. — no unit suffix or use the DP's own */
    if (p->primary_dp == OPENDASH_DP_RPM) return "rpm";
    return "";
}

static const char* get_secondary_suffix(uint8_t page)
{
    if (page >= GAUGE_PAGE_COUNT) return "";
    const gauge_page_t *p = &s_gauge_pages[page];
    if (p->is_secondary_temp)     return opendash_get_temp_suffix(current_layout.temp_unit);
    if (p->is_secondary_pressure) return opendash_get_pressure_suffix(current_layout.pressure_unit);
    if (p->is_secondary_speed)    return opendash_get_speed_suffix(current_layout.speed_unit);
    if (p->secondary_dp == OPENDASH_DP_AFR) return ":1";
    return "";
}

static float convert_primary(uint8_t page, float raw)
{
    if (page >= GAUGE_PAGE_COUNT) return raw;
    const gauge_page_t *p = &s_gauge_pages[page];
    if (p->is_primary_temp)     return opendash_convert_temp(raw, current_layout.temp_unit);
    if (p->is_primary_pressure) return opendash_convert_pressure(raw, current_layout.pressure_unit);
    if (p->is_primary_speed)    return opendash_convert_speed(raw, current_layout.speed_unit);
    return raw;
}

static float convert_secondary(uint8_t page, float raw)
{
    if (page >= GAUGE_PAGE_COUNT) return raw;
    const gauge_page_t *p = &s_gauge_pages[page];
    if (p->is_secondary_temp)     return opendash_convert_temp(raw, current_layout.temp_unit);
    if (p->is_secondary_pressure) return opendash_convert_pressure(raw, current_layout.pressure_unit);
    if (p->is_secondary_speed)    return opendash_convert_speed(raw, current_layout.speed_unit);
    return raw;
}

/* ======================================================================
 * OUTLINED TEXT HELPERS
 *
 * LVGL doesn't have native text outline.  We create 4 shadow labels at
 * 1px offsets behind the main label to simulate an outline.
 * ====================================================================== */

static lv_obj_t* create_outlined_label(lv_obj_t *parent, const char *text,
                                        opendash_font_size_t font_size,
                                        uint32_t text_color, uint32_t outline_color,
                                        int8_t outline_px)
{
    lv_obj_t *container = lv_obj_create(parent);
    lv_obj_remove_style_all(container);
    lv_obj_set_size(container, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_style_pad_all(container, outline_px, 0);
    lv_obj_clear_flag(container, LV_OBJ_FLAG_SCROLLABLE);

    const int8_t offsets[4][2] = {
        {0, outline_px}, {outline_px * 2, outline_px},
        {outline_px, 0}, {outline_px, outline_px * 2}
    };
    for (int i = 0; i < 4; i++) {
        lv_obj_t *shadow = lv_label_create(container);
        lv_label_set_text(shadow, text);
        opendash_set_font(shadow, font_size);
        lv_obj_set_style_text_color(shadow, lv_color_hex(outline_color), 0);
        lv_obj_set_pos(shadow, offsets[i][0], offsets[i][1]);
    }

    lv_obj_t *main_label = lv_label_create(container);
    lv_label_set_text(main_label, text);
    opendash_set_font(main_label, font_size);
    lv_obj_set_style_text_color(main_label, lv_color_hex(text_color), 0);
    lv_obj_set_pos(main_label, outline_px, outline_px);

    return container;
}

/**
 * @brief Update all labels inside an outlined label container.
 *
 * Checks if text actually changed before calling lv_label_set_text
 * to avoid unnecessary LVGL invalidation (which can starve IDLE0 -> WDT).
 */
static void update_outlined_text(lv_obj_t *container, const char *new_text)
{
    if (container == NULL || new_text == NULL) return;
    uint32_t count = lv_obj_get_child_count(container);
    for (uint32_t i = 0; i < count; i++) {
        lv_obj_t *child = lv_obj_get_child(container, i);
        if (child && lv_obj_check_type(child, &lv_label_class)) {
            /* Only update if text actually changed — avoids invalidation storm */
            const char *cur = lv_label_get_text(child);
            if (cur == NULL || strcmp(cur, new_text) != 0) {
                lv_label_set_text(child, new_text);
            }
        }
    }
}

/* ======================================================================
 * SCREEN 1 — GAUGE MODE (shared by all gauge pages)
 *
 * Layout (see ASCII art at top of file):
 *   1  White outline arc — ARC_SIZE px, symmetric outline
 *   2  Colored indicator arc — ARC_SIZE px (same size, thinner width)
 *   3  Primary label ("OIL PRESS") — centered, y = PRIMARY_LABEL_Y
 *   4  Primary value ("47.2") — centered, y = PRIMARY_VALUE_Y
 *   5  Primary unit ("psi") — centered, y = PRIMARY_UNIT_Y
 *   6  Min/Max text ("MIN: 32  MAX: 68") — centered, y = PRIMARY_MINMAX_Y
 *   7  Secondary box — bordered rectangle, y = SECONDARY_BOX_Y
 *   8  Secondary label ("BOOST") — top-left of box
 *   9  Secondary value ("14.7") — centered in box
 *  10  Secondary unit ("kPa") — bottom-right of box
 * ====================================================================== */

static void create_gauge_screen(void)
{
    screen_gauge = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(screen_gauge, lv_color_hex(0x000000), 0);

#if HAS_BACKGROUND_IMAGE
    lv_obj_t *bg = lv_image_create(screen_gauge);
    lv_image_set_src(bg, &background_right_dsc);
    lv_obj_set_size(bg, LCD_H_RES, LCD_V_RES);
    lv_obj_center(bg);
    lv_obj_set_style_image_opa(bg, 76, 0);
    lv_obj_move_to_index(bg, 0);
#endif

    /* -- 1) White outline arc (BEHIND colored arc) --
     *    LARGER bounding box than colored arc → extends outside.
     *    WIDER stroke than colored arc → extends inside.
     *    Net result: symmetric 5px border on both sides.
     */
    arc_outline = lv_arc_create(screen_gauge);
    lv_obj_set_size(arc_outline, ARC_OUTLINE_SIZE, ARC_OUTLINE_SIZE);
    lv_obj_align(arc_outline, LV_ALIGN_CENTER, 0, ARC_Y_OFFSET);
    lv_arc_set_rotation(arc_outline, ARC_ROTATION_DEG);
    lv_arc_set_bg_angles(arc_outline, 0, ARC_SWEEP_DEG);
    lv_arc_set_value(arc_outline, 0);
    lv_arc_set_range(arc_outline, 0, 100);
    lv_obj_remove_style(arc_outline, NULL, LV_PART_KNOB);
    lv_obj_remove_style(arc_outline, NULL, LV_PART_INDICATOR);
    lv_obj_clear_flag(arc_outline, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_arc_width(arc_outline,
                               ARC_OUTLINE_WIDTH,
                               LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc_outline, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_arc_rounded(arc_outline, true, LV_PART_MAIN);

    /* -- 2) Colored indicator arc (ON TOP of outline) --
     *    Smaller bounding box → inset from outline on outside.
     *    Thinner width → inset from outline on inside.
     */
    arc_gauge = lv_arc_create(screen_gauge);
    lv_obj_set_size(arc_gauge, ARC_SIZE, ARC_SIZE);
    lv_obj_align(arc_gauge, LV_ALIGN_CENTER, 0, ARC_Y_OFFSET);
    lv_arc_set_rotation(arc_gauge, ARC_ROTATION_DEG);
    lv_arc_set_bg_angles(arc_gauge, 0, ARC_SWEEP_DEG);
    lv_arc_set_value(arc_gauge, 0);
    lv_arc_set_range(arc_gauge, 0, 100);
    lv_obj_remove_style(arc_gauge, NULL, LV_PART_KNOB);
    lv_obj_clear_flag(arc_gauge, LV_OBJ_FLAG_CLICKABLE);
    /* Background track (unfilled) */
    lv_obj_set_style_arc_width(arc_gauge, ARC_WIDTH, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc_gauge, lv_color_hex(OPENDASH_COLOR_BG_SECTION), LV_PART_MAIN);
    lv_obj_set_style_arc_rounded(arc_gauge, true, LV_PART_MAIN);
    /* Indicator (filled sweep) */
    lv_obj_set_style_arc_width(arc_gauge, ARC_WIDTH, LV_PART_INDICATOR);
    lv_obj_set_style_arc_color(arc_gauge, lv_color_hex(0x00AAFF), LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(arc_gauge, true, LV_PART_INDICATOR);

    /* -- 3) Primary label -- */
    primary_label = create_outlined_label(screen_gauge, "---",
                                           OPENDASH_FONT_SIZE_MEDIUM,
                                           OPENDASH_COLOR_TEXT_SECONDARY,
                                           OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(primary_label, LV_ALIGN_CENTER, 0, PRIMARY_LABEL_Y);

    /* -- 4) Primary value -- */
    primary_value = create_outlined_label(screen_gauge, "---",
                                           OPENDASH_FONT_SIZE_XXLARGE,
                                           OPENDASH_COLOR_TEXT_PRIMARY,
                                           OPENDASH_COLOR_TEXT_OUTLINE, 2);
    lv_obj_align(primary_value, LV_ALIGN_CENTER, 0, PRIMARY_VALUE_Y);

    /* -- 5) Primary unit suffix -- */
    primary_unit = create_outlined_label(screen_gauge, "",
                                          OPENDASH_FONT_SIZE_SMALL,
                                          OPENDASH_COLOR_TEXT_SECONDARY,
                                          OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(primary_unit, LV_ALIGN_CENTER, 0, PRIMARY_UNIT_Y);

    /* -- 6) Min/Max display -- */
    primary_minmax = create_outlined_label(screen_gauge, "",
                                            OPENDASH_FONT_SIZE_SMALL,
                                            OPENDASH_COLOR_TEXT_SECONDARY,
                                            OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(primary_minmax, LV_ALIGN_CENTER, 0, PRIMARY_MINMAX_Y);

    /* -- 7) Secondary box -- */
    secondary_box = lv_obj_create(screen_gauge);
    lv_obj_set_size(secondary_box, SECONDARY_BOX_W, SECONDARY_BOX_H);
    lv_obj_align(secondary_box, LV_ALIGN_CENTER, 0, SECONDARY_BOX_Y);
    lv_obj_set_style_bg_color(secondary_box, lv_color_hex(0x181818), 0);
    lv_obj_set_style_bg_opa(secondary_box, 242, 0);
    lv_obj_set_style_border_color(secondary_box, lv_color_hex(0x404040), 0);
    lv_obj_set_style_border_width(secondary_box, SECONDARY_BOX_BORDER, 0);
    lv_obj_set_style_radius(secondary_box, SECONDARY_BOX_RADIUS, 0);
    lv_obj_set_style_pad_all(secondary_box, 0, 0);
    lv_obj_clear_flag(secondary_box, LV_OBJ_FLAG_SCROLLABLE);

    /* -- 8) Secondary label -- */
    secondary_label = create_outlined_label(secondary_box, "---",
                                             OPENDASH_FONT_SIZE_MEDIUM,
                                             OPENDASH_COLOR_TEXT_SECONDARY,
                                             OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(secondary_label, LV_ALIGN_TOP_LEFT,
                 SECONDARY_LABEL_X, SECONDARY_LABEL_Y);

    /* -- 9) Secondary value -- */
    secondary_value = create_outlined_label(secondary_box, "---",
                                             OPENDASH_FONT_SIZE_XLARGE,
                                             OPENDASH_COLOR_TEXT_PRIMARY,
                                             OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(secondary_value, LV_ALIGN_CENTER, 0, SECONDARY_VALUE_Y);

    /* -- 10) Secondary unit -- */
    secondary_unit = create_outlined_label(secondary_box, "",
                                            OPENDASH_FONT_SIZE_MEDIUM,
                                            OPENDASH_COLOR_TEXT_SECONDARY,
                                            OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(secondary_unit, LV_ALIGN_BOTTOM_RIGHT,
                 SECONDARY_UNIT_X, SECONDARY_UNIT_Y);

    ESP_LOGI(TAG, "Gauge screen created (arc %dpx, outline %dpx, +/-%dpx symmetric)",
             ARC_SIZE, ARC_OUTLINE_SIZE, ARC_OUTLINE_EXTRA);
}

/**
 * @brief Apply a gauge page — swaps labels, unit suffixes, resets arc.
 *
 * Called on page switch or at init for page 0.
 * Does NOT create/destroy widgets, just updates text content.
 */
static void apply_gauge_page(uint8_t page)
{
    if (page >= GAUGE_PAGE_COUNT) return;
    const gauge_page_t *gp = &s_gauge_pages[page];

    /* Swap labels and unit suffixes */
    update_outlined_text(primary_label, gp->primary_label);
    update_outlined_text(primary_value, "---");
    update_outlined_text(primary_unit,  get_primary_suffix(page));

    update_outlined_text(secondary_label, gp->secondary_label);
    update_outlined_text(secondary_value, "---");
    update_outlined_text(secondary_unit,  get_secondary_suffix(page));

    /* Show min/max if we have data for this page */
    if (s_minmax[page].has_data) {
        char mm[48];
        float mn = convert_primary(page, s_minmax[page].primary_min);
        float mx = convert_primary(page, s_minmax[page].primary_max);
        snprintf(mm, sizeof(mm), "MIN:%.0f  MAX:%.0f", mn, mx);
        update_outlined_text(primary_minmax, mm);
    } else {
        update_outlined_text(primary_minmax, "");
    }

    /* Reset arc to 0 */
    lv_arc_set_value(arc_gauge, 0);

    /* Reset shift-light state */
    s_shift_active = false;
    s_shift_blink_on = false;
    /* Restore normal arc color */
    lv_obj_set_style_arc_color(arc_gauge, lv_color_hex(0x00AAFF), LV_PART_INDICATOR);

    ESP_LOGI(TAG, "Gauge page %d: %s + %s", page,
             gp->primary_label, gp->secondary_label);
}

/* ======================================================================
 * ODOMETER SCREEN (final screen)
 * ====================================================================== */

static void create_odo_screen(void)
{
    screen_odo = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(screen_odo, lv_color_hex(0x000000), 0);

#if HAS_BACKGROUND_IMAGE
    lv_obj_t *bg = lv_image_create(screen_odo);
    lv_image_set_src(bg, &background_right_dsc);
    lv_obj_set_size(bg, LCD_H_RES, LCD_V_RES);
    lv_obj_center(bg);
    lv_obj_set_style_image_opa(bg, 76, 0);
    lv_obj_move_to_index(bg, 0);
#endif

    odo_label = create_outlined_label(screen_odo, "ODOMETER",
                                       OPENDASH_FONT_SIZE_MEDIUM,
                                       OPENDASH_COLOR_TEXT_SECONDARY,
                                       OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(odo_label, LV_ALIGN_CENTER, 0, ODO_LABEL_Y);

    odo_value = create_outlined_label(screen_odo, "0.0 km",
                                       OPENDASH_FONT_SIZE_XLARGE,
                                       OPENDASH_COLOR_TEXT_PRIMARY,
                                       OPENDASH_COLOR_TEXT_OUTLINE, 2);
    lv_obj_align(odo_value, LV_ALIGN_CENTER, 0, ODO_VALUE_Y);

    trip_box = lv_obj_create(screen_odo);
    lv_obj_set_size(trip_box, TRIP_BOX_W, TRIP_BOX_H);
    lv_obj_align(trip_box, LV_ALIGN_CENTER, 0, TRIP_BOX_Y);
    lv_obj_set_style_bg_color(trip_box, lv_color_hex(0x181818), 0);
    lv_obj_set_style_bg_opa(trip_box, 242, 0);
    lv_obj_set_style_border_color(trip_box, lv_color_hex(0x404040), 0);
    lv_obj_set_style_border_width(trip_box, SECONDARY_BOX_BORDER, 0);
    lv_obj_set_style_radius(trip_box, SECONDARY_BOX_RADIUS, 0);
    lv_obj_set_style_pad_all(trip_box, 0, 0);
    lv_obj_clear_flag(trip_box, LV_OBJ_FLAG_SCROLLABLE);

    trip_label = create_outlined_label(trip_box, "TRIP A",
                                        OPENDASH_FONT_SIZE_MEDIUM,
                                        OPENDASH_COLOR_TEXT_SECONDARY,
                                        OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(trip_label, LV_ALIGN_TOP_MID, 0, TRIP_LABEL_Y);

    trip_value = create_outlined_label(trip_box, "0.0 km",
                                        OPENDASH_FONT_SIZE_LARGE,
                                        OPENDASH_COLOR_TEXT_PRIMARY,
                                        OPENDASH_COLOR_TEXT_OUTLINE, 1);
    lv_obj_align(trip_value, LV_ALIGN_CENTER, 0, TRIP_VALUE_Y);

    ESP_LOGI(TAG, "Odometer screen created");
}

/* ======================================================================
 * WARNING OVERLAY — flashing red/orange fullscreen
 * ====================================================================== */

static void warning_flash_timer_cb(lv_timer_t *timer)
{
    (void)timer;
    if (warning_overlay == NULL) return;

    uint32_t elapsed = esp_log_timestamp() - warning_flash_start;
    if (warning_flash_duration > 0 && elapsed > warning_flash_duration) {
        ui_manager_warning_clear();
        return;
    }
    bool visible = ((elapsed / WARNING_FLASH_MS) % 2) == 0;
    if (visible) lv_obj_remove_flag(warning_overlay, LV_OBJ_FLAG_HIDDEN);
    else         lv_obj_add_flag(warning_overlay, LV_OBJ_FLAG_HIDDEN);
}

static void create_warning_overlay_on_screen(lv_obj_t *screen)
{
    if (warning_overlay != NULL) lv_obj_delete(warning_overlay);

    warning_overlay = lv_obj_create(screen);
    lv_obj_set_size(warning_overlay, LCD_H_RES, LCD_V_RES);
    lv_obj_center(warning_overlay);
    uint32_t color = (warning_level == OPENDASH_WARNING_CRITICAL)
                     ? OPENDASH_COLOR_WARNING_BOX_RED
                     : OPENDASH_COLOR_WARNING_BOX_ORANGE;
    lv_obj_set_style_bg_color(warning_overlay, lv_color_hex(color), 0);
    lv_obj_set_style_bg_opa(warning_overlay, 180, 0);
    lv_obj_set_style_border_width(warning_overlay, 0, 0);
    lv_obj_set_style_radius(warning_overlay, 0, 0);
    lv_obj_clear_flag(warning_overlay, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(warning_overlay, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_move_foreground(warning_overlay);
}

/* ======================================================================
 * SHIFT-LIGHT — blinks arc color when RPM exceeds threshold
 *
 * Called from update_value when the current page has shift_light=true
 * and the arc percentage exceeds SHIFT_BLINK_THRESHOLD.
 * ====================================================================== */

static void shift_light_update(int arc_pct)
{
    if (current_page >= GAUGE_PAGE_COUNT) return;
    const gauge_page_t *gp = &s_gauge_pages[current_page];
    if (!gp->shift_light) return;

    if (arc_pct >= SHIFT_BLINK_THRESHOLD) {
        uint32_t now = esp_log_timestamp();
        if (!s_shift_active) {
            s_shift_active = true;
            s_shift_last_toggle_ms = now;
            s_shift_blink_on = true;
        }
        if (now - s_shift_last_toggle_ms >= SHIFT_BLINK_INTERVAL_MS) {
            s_shift_last_toggle_ms = now;
            s_shift_blink_on = !s_shift_blink_on;
        }
        /* Toggle between red and blue */
        uint32_t color = s_shift_blink_on ? 0xFF0000 : 0x00AAFF;
        lv_obj_set_style_arc_color(arc_gauge, lv_color_hex(color), LV_PART_INDICATOR);
    } else if (s_shift_active) {
        /* Dropped below threshold — restore normal color */
        s_shift_active = false;
        s_shift_blink_on = false;
        lv_obj_set_style_arc_color(arc_gauge, lv_color_hex(0x00AAFF), LV_PART_INDICATOR);
    }
}

/* ======================================================================
 * UI TASK — runs LVGL timer handler on core 1
 *
 * NOTE: uses display_lvgl_lock() to protect LVGL objects.  The main loop
 * on core 0 also locks before calling ui_manager_update_*.
 * ====================================================================== */

extern bool display_lvgl_lock(uint32_t timeout_ms);
extern void display_lvgl_unlock(void);

static void ui_task(void *pvParameters)
{
    ESP_LOGI(TAG, "UI task started on core 1");
    while (1) {
        if (display_lvgl_lock(50)) {
            lv_timer_handler();
            display_lvgl_unlock();
        }
        vTaskDelay(pdMS_TO_TICKS(20));
    }
}

/* ======================================================================
 * PUBLIC API — Initialization
 * ====================================================================== */

esp_err_t ui_manager_init(const opendash_display_layout_t *layout)
{
    if (layout == NULL) {
        ESP_LOGE(TAG, "Layout pointer is NULL");
        return ESP_ERR_INVALID_ARG;
    }
    memcpy(&current_layout, layout, sizeof(opendash_display_layout_t));

    /* Clear min/max tracking */
    memset(s_minmax, 0, sizeof(s_minmax));

    ESP_LOGI(TAG, "Creating multi-page UI for 480x480 round display");
    ESP_LOGI(TAG, "  %d gauge pages + 1 odometer = %d total screens",
             (int)GAUGE_PAGE_COUNT, (int)TOTAL_SCREEN_COUNT);
    ESP_LOGI(TAG, "  Units: temp=%s speed=%s pressure=%s distance=%s",
             opendash_get_temp_suffix(layout->temp_unit),
             opendash_get_speed_suffix(layout->speed_unit),
             opendash_get_pressure_suffix(layout->pressure_unit),
             opendash_get_distance_suffix(layout->distance_unit));

    create_gauge_screen();
    create_odo_screen();

    /* Start on page 0 (first gauge page) */
    current_page = 0;
    apply_gauge_page(0);
    lv_screen_load(screen_gauge);

    ESP_LOGI(TAG, "UI initialized — boot button cycles %d screens",
             (int)TOTAL_SCREEN_COUNT);
    return ESP_OK;
}

esp_err_t ui_manager_start(void)
{
    BaseType_t ret = xTaskCreatePinnedToCore(
        ui_task, "ui_task", 8192, NULL, 5, &ui_task_handle, 1);
    if (ret != pdPASS) {
        ESP_LOGE(TAG, "Failed to create UI task");
        return ESP_FAIL;
    }
    ESP_LOGI(TAG, "UI task started (core 1, 50Hz, LVGL-locked)");
    return ESP_OK;
}

void ui_manager_suspend(void)
{
    if (ui_task_handle) {
        vTaskSuspend(ui_task_handle);
        ESP_LOGW(TAG, "UI task suspended (BLE OTA)");
    }
}

/* ======================================================================
 * PUBLIC API — Data Updates (page-aware)
 *
 * Only updates widgets if the incoming data_point_id matches the
 * current gauge page's primary or secondary assignment.  This avoids
 * wasting CPU on updates the user can't see.
 * ====================================================================== */

void ui_manager_update_value(uint16_t data_point_id, float value)
{
    /* Skip if on odometer screen — gauge widgets aren't visible */
    if (current_page >= GAUGE_PAGE_COUNT) return;

    const gauge_page_t *gp = &s_gauge_pages[current_page];
    char buf[32];

    /* --- Primary (arc) value --- */
    if (data_point_id == gp->primary_dp) {
        float display_val = convert_primary(current_page, value);

        /* Format: temperature = no decimals, pressure = 1 decimal, RPM = no decimals */
        if (gp->is_primary_temp || gp->primary_dp == OPENDASH_DP_RPM) {
            snprintf(buf, sizeof(buf), "%.0f", display_val);
        } else {
            snprintf(buf, sizeof(buf), "%.1f", display_val);
        }
        update_outlined_text(primary_value, buf);

        /* Update arc percentage: map raw value to 0-100% */
        float range = gp->arc_max - gp->arc_min;
        int pct = (range > 0.0f) ? (int)(((value - gp->arc_min) / range) * 100.0f) : 0;
        if (pct < 0) pct = 0;
        if (pct > 100) pct = 100;
        lv_arc_set_value(arc_gauge, pct);

        /* Track session min/max (in raw/internal units) */
        page_minmax_t *mm = &s_minmax[current_page];
        if (!mm->has_data) {
            mm->primary_min = value;
            mm->primary_max = value;
            mm->has_data = true;
        } else {
            if (value < mm->primary_min) mm->primary_min = value;
            if (value > mm->primary_max) mm->primary_max = value;
        }
        /* Update min/max display */
        float mn = convert_primary(current_page, mm->primary_min);
        float mx = convert_primary(current_page, mm->primary_max);
        snprintf(buf, sizeof(buf), "MIN:%.0f  MAX:%.0f", mn, mx);
        update_outlined_text(primary_minmax, buf);

        /* Shift-light check */
        shift_light_update(pct);
        return;
    }

    /* --- Secondary (box) value --- */
    if (data_point_id == gp->secondary_dp) {
        float display_val = convert_secondary(current_page, value);
        if (gp->is_secondary_speed || gp->secondary_dp == OPENDASH_DP_RPM) {
            snprintf(buf, sizeof(buf), "%.0f", display_val);
        } else if (gp->secondary_dp == OPENDASH_DP_AFR) {
            snprintf(buf, sizeof(buf), "%.1f", display_val);
        } else {
            snprintf(buf, sizeof(buf), "%.1f", display_val);
        }
        update_outlined_text(secondary_value, buf);
        return;
    }

    /* Data point not on current page — silently ignore */
}

/* ======================================================================
 * PUBLIC API — Odometer Update
 *
 * Only updates LVGL labels when the odometer screen is actually visible.
 * Adds taskYIELD() between the two outlined-text updates to let the
 * IDLE task run briefly and prevent WDT starvation on CPU 0.
 * ====================================================================== */

void ui_manager_update_odometer(const opendash_odometer_t *odo)
{
    if (odo == NULL) return;

    /* Guard: only update when ODO screen is visible.
     * Writing to invisible labels still triggers lv_obj_invalidate
     * which monopolizes CPU 0 -> starves IDLE0 -> WDT crash.        */
    if (current_page != ODO_SCREEN_INDEX) return;

    char buf[32];
    const char *suffix = opendash_get_distance_suffix(current_layout.distance_unit);

    /* Odometer total */
    float total = opendash_convert_distance(
        opendash_odometer_get_km(odo), current_layout.distance_unit);
    snprintf(buf, sizeof(buf), "%.1f %s", total, suffix);
    update_outlined_text(odo_value, buf);

    /* Yield between the two heavy outlined-text updates to let IDLE0 run.
     * Each update touches 5 labels (4 shadow + 1 main) and triggers
     * LVGL invalidation; doing both back-to-back can starve IDLE for
     * >5 seconds on a loaded system -> WDT timeout.                     */
    taskYIELD();

    /* Trip A */
    float trip = opendash_convert_distance(
        opendash_odometer_get_trip_a_km(odo), current_layout.distance_unit);
    snprintf(buf, sizeof(buf), "%.1f %s", trip, suffix);
    update_outlined_text(trip_value, buf);
}

/* ======================================================================
 * PUBLIC API — Warning System
 * ====================================================================== */

esp_err_t ui_manager_warning_trigger(opendash_warning_level_t level,
                                      const char *message,
                                      uint32_t flash_ms)
{
    (void)message;
    warning_level = level;
    warning_flash_duration = flash_ms;
    warning_flash_start = esp_log_timestamp();

    lv_obj_t *active = (current_page < GAUGE_PAGE_COUNT) ? screen_gauge : screen_odo;
    create_warning_overlay_on_screen(active);

    if (warning_timer == NULL) {
        warning_timer = lv_timer_create(warning_flash_timer_cb, WARNING_FLASH_MS, NULL);
    }
    ESP_LOGI(TAG, "Warning triggered: level=%d, duration=%lu ms",
             level, (unsigned long)flash_ms);
    return ESP_OK;
}

esp_err_t ui_manager_warning_clear(void)
{
    if (warning_timer != NULL) {
        lv_timer_delete(warning_timer);
        warning_timer = NULL;
    }
    if (warning_overlay != NULL) {
        lv_obj_delete(warning_overlay);
        warning_overlay = NULL;
    }
    warning_level = OPENDASH_WARNING_NONE;
    ESP_LOGI(TAG, "Warning cleared");
    return ESP_OK;
}

/* ======================================================================
 * PUBLIC API — Screen Navigation
 *
 * Screens cycle: Gauge[0] -> Gauge[1] -> ... -> Gauge[N-1] -> ODO -> Gauge[0]
 * ====================================================================== */

esp_err_t ui_manager_next_screen(void)
{
    uint8_t next = (current_page + 1) % TOTAL_SCREEN_COUNT;

    /* Clear any active warning */
    ui_manager_warning_clear();

    current_page = next;

    if (next < GAUGE_PAGE_COUNT) {
        apply_gauge_page(next);
        lv_screen_load(screen_gauge);
        ESP_LOGI(TAG, "Switched to GAUGE page %d/%d (%s + %s)",
                 next, (int)GAUGE_PAGE_COUNT,
                 s_gauge_pages[next].primary_label,
                 s_gauge_pages[next].secondary_label);
    } else {
        lv_screen_load(screen_odo);
        ESP_LOGI(TAG, "Switched to ODOMETER screen");
    }

    return ESP_OK;
}

uint8_t ui_manager_get_current_screen(void)
{
    return current_page;
}

uint8_t ui_manager_get_screen_count(void)
{
    return (uint8_t)TOTAL_SCREEN_COUNT;
}
