#!/usr/bin/env bash
# Licensed under Sovereign Individual License v1.0 — see LICENSE file
# ─────────────────────────────────────────────────────────────────────────────
# fleet-clean.sh — local swamp cleanup (A+ program P0.5). WHY: the working tree
# carries ~2.9 GB of regenerable idf.py build dirs across 12 nodes plus stale
# sdkconfig.old files; that swamp hides the real tree size from `du` honesty
# and slows IDE indexing/backups. This script is idempotent.
#
# Dry-run by default (prints what it WOULD do). `--force` actually deletes.
# Never touches: tearing-logs/ (referenced by TEARING.md — size printed only),
# .venv/.venv-ota (reported with recreate hints; Python envs are yours),
# anything under git (sources, docs, nested .gitignore files).
#
# Usage:  bash scripts/fleet-clean.sh          # dry run
#         bash scripts/fleet-clean.sh --force  # act
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

echo "fleet-clean: mode=$([ $FORCE -eq 1 ] && echo FORCE || echo DRY-RUN)"

# 1) Stale build dirs (regenerated by `idf.py build`)
for d in center left right gps pod1 pod2 openDstream mos-4ch-a mos-4ch-b \
         relay-4ch-hd relay-8ch-a relay-8ch-b test; do
    if [ -d "$d/build" ]; then
        sz=$(du -sh "$d/build" | cut -f1)
        if [ $FORCE -eq 1 ]; then rm -rf "$d/build"; echo "  deleted  $d/build ($sz)";
        else echo "  would delete $d/build ($sz)"; fi
    fi
done

# 2) Stale sdkconfig.old files
for f in */sdkconfig.old; do
    [ -e "$f" ] || continue
    if [ $FORCE -eq 1 ]; then rm -f "$f"; echo "  deleted  $f";
    else echo "  would delete $f"; fi
done

# 3) Stray binaries/elfs outside build dirs (tracked ones are NOT touched —
#    git ls-files check keeps this honest). Exclusions: regenerable dependency
#    trees (managed_components/, node_modules/) are OFF-LIMITS — even though
#    ignored, they are not ours to prune. (Found live 2026-10-07: the first
#    --force run pruned some lvgl test .bin files inside managed_components;
#    regenerable, so no harm — and now prevented.)
for f in $(git ls-files --others --ignored --exclude-standard | grep -E '\.(bin|elf)$' | grep -vE 'managed_components/|node_modules/' || true); do
    case "$f" in */build/*|build/*) continue;; esac
    if [ $FORCE -eq 1 ]; then rm -f "$f"; echo "  deleted  $f (ignored stray binary)";
    else echo "  would delete $f (ignored stray binary)"; fi
done

# 4) Report venvs (never auto-deleted — recreate from common/fonts/package.json
#    tooling / the OTA script's pip needs when needed)
for v in .venv .venv-ota; do
    [ -d "$v" ] && echo "  REPORT   $v ($(du -sh "$v" | cut -f1)) — recreate from requirements/package files if desired, not auto-deleted"
done

# 5) tearing-logs/ — keep (referenced by TEARING.md), print size
[ -d tearing-logs ] && echo "  REPORT   tearing-logs/ ($(du -sh tearing-logs | cut -f1)) — kept by design (TEARING.md references)"

echo "fleet-clean: done. Verify with: du -sh ."